version: "3.7"

services:
  postgres14:
    platform: linux/amd64
    image: postgres:14
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 15434:5432

